### ISSUE TITLE
로그인 실패 시 안내 팝업 창이 중첩됨

### ISSUE THREAD

**Issue by MoerAI** [osamhack2020/Web_SpecialForces_SpecialWarrior#1]
![스크린샷, 2020-10-19 22-59-01](https://user-images.githubusercontent.com/26067127/96461229-177a0d80-125f-11eb-88c2-d9733fde3210.png)
로그인 실패 시 안내 팝업 창이 중첩되어 나타나며 파란색으로 알 수 없는 창도 나타남

**Comment by 0chil** [comment]
해결완료
