### ISSUE TITLE
회원가입 폼 입력시 군번 및 전화번호는 int로 통일 할 것

### ISSUE THREAD

**Issue by MoerAI** [osamhack2020/Web_SpecialForces_SpecialWarrior#2]
![스크린샷, 2020-10-19 22-59-18](https://user-images.githubusercontent.com/26067127/96461549-7a6ba480-125f-11eb-86dc-aad1c135ad14.png)
군번에 -와 전화번호의 -, *같은  특수기호의 입력은 사전에 입력되지 않도록 개발 할 것.

**Comment by 0chil** [comment]
Primary key가 아니며, 보여주기 위한 용도이므로 상관없다고 판단. 해결완료
